export const MOCK_CANDIDATES = [
  {
    id: 1,
    submission_date: "2026-07-01T10:15:30Z",
    full_name: "Aarav Mehta",
    email: "aarav.mehta@university.edu",
    phone: "+91 98765 43210",
    linkedin: "https://linkedin.com/in/aaravmehta",
    location: "Mumbai, India",
    preferred_start_date: "2026-08-15",
    education_level: "B.Tech",
    ug_university: "IIT Bombay",
    masters_university: null,
    course_major: "Computer Science",
    degree_status: "Graduated",
    completion_year: 2025,
    programming_languages: "Python, C++, Javascript, Go",
    aiml_experience: "2 Years",
    claude_ecosystem: "Tier 3",
    skill_python: 5,
    skill_deep_learning: 4,
    skill_nlp: 4,
    skill_computer_vision: 3,
    skill_reinforcement_learning: 2,
    skill_multimodal_ai: 4,
    skill_finetuning_lora_peft: 4,
    skill_llm_orchestration: 5,
    skill_agent_fundamentals: 5,
    skill_mcp: 4,
    skill_embeddings_vector_rag: 5,
    skill_reasoning_models: 4,
    skill_evals: 3,
    skill_ai_coding_tools: 5,
    skill_rag: 5,
    current_project: "Multi-agent repository analyzer using MCP server protocols to parse dependency trees.",
    project_state: "Production",
    project_category: "AI Coding Agents",
    demo_link: "https://demo.aarav.dev",
    github_url: "https://github.com/aaravmehta/mcp-analyzer",
    preferred_industry: "Artificial Intelligence",
    open_to_onsite: "Yes",
    open_to_travel: "Yes",
    anything_else: "Highly interested in generative AI orchestration.",
    applied_role: "ML Engineer Intern",
    job_id: "JOB-ML-01",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-aarav/view",
    resume_filename: "Aarav_Mehta_Resume.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Male",
      cat: "UG",
      graduation: "2025",
      tier: "T1+",
      total: 19.5,
      edu: 5.0,
      exp: 4.5,
      proj: 5.0,
      substance: 4.5,
      deploy: 5.0,
      artifact: 2.0,
      skills: 4.0,
      domain: "GenAI Orchestration",
      degree: "B.Tech CS",
      stream: "Computer Science",
      college: "IIT Bombay",
      location: "Mumbai",
      ai_proj: 5.0,
      fs_proj: 4.0,
      intern_mo: 6.0,
      co_tier: 1.0,
      deploy_stage: "Production Vercel",
      num_skills: 12,
      claude_lvl: "Advanced",
      aiml_exp: "24 months relevant AI project build time",
      demo_explanation: "Advanced MCP server codebase connecting vector databases to agent networks.",
      demo_review_notes_ai: "Claude Evaluation: Aarav displays state-of-the-art understanding of Model Context Protocol (MCP) and multi-agent interaction. Excellent codebase structure, solid typescript implementation, proper error boundaries. Code is clean and modular. Highly recommended for immediate interview advancement.",
      mg_review: "Audited - scores look accurate.",
      mg_interview_priority: "High",
      review_comments: "Incredible AI portfolio. Code structure looks professional.",
      app_status: "Yes",
      eval_group: "Dharti"
    },
    round_2_evaluation: {
      when_can_they_start: "15-08-2026",
      duration_months: "6 months",
      demo_review_comment: "The candidate demonstrated the multi-agent orchestration setup in real-time. Depth of build is high, candidate clearly understands asynchronous worker coordination and caching layers.",
      product_depth: "Deep technical architecture utilizing Redis and queues.",
      complexity: "High",
      tech_stack: "TypeScript, Python, FastAPI, Redis, Supabase",
      solves_business_problem: "Yes",
      moved_to_round_3: "Yes"
    },
    round_3_evaluation: {
      review_comments: "Excellent cultural fit and raw problem-solving capability. Strong design patterns knowledge.",
      final_status: "Yes"
    }
  },
  {
    id: 2,
    submission_date: "2026-07-02T11:30:10Z",
    full_name: "Sofia Rodriguez",
    email: "sofia.rod@state.edu",
    phone: "+1 415 555 0192",
    linkedin: "https://linkedin.com/in/sofiarod",
    location: "San Francisco, USA",
    preferred_start_date: "2026-09-01",
    education_level: "M.S.",
    ug_university: "UC Berkeley",
    masters_university: "Stanford University",
    course_major: "Data Science",
    degree_status: "Ongoing",
    completion_year: 2026,
    programming_languages: "Python, R, SQL, PyTorch",
    aiml_experience: "1 Year",
    claude_ecosystem: "Tier 2",
    skill_python: 4,
    skill_deep_learning: 5,
    skill_nlp: 5,
    skill_computer_vision: 2,
    skill_reinforcement_learning: 2,
    skill_multimodal_ai: 3,
    skill_finetuning_lora_peft: 4,
    skill_llm_orchestration: 3,
    skill_agent_fundamentals: 3,
    skill_mcp: 2,
    skill_embeddings_vector_rag: 4,
    skill_reasoning_models: 3,
    skill_evals: 4,
    skill_ai_coding_tools: 4,
    skill_rag: 4,
    current_project: "Fine-tuning Llama-3 models on legal compliance documents using LoRA and PEFT techniques.",
    project_state: "Staging",
    project_category: "LLM Fine-tuning",
    demo_link: "https://huggingface.co/spaces/sofiarod/legal-finetuner",
    github_url: "https://github.com/sofiarod/legal-peft",
    preferred_industry: "LegalTech / FinTech",
    open_to_onsite: "Yes",
    open_to_travel: "Negotiable",
    anything_else: "Looking for an internship before graduating in Spring 2026.",
    applied_role: "AI Research Intern",
    job_id: "JOB-AI-02",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-sofia/view",
    resume_filename: "Sofia_Rodriguez_Resume.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Female",
      cat: "PG",
      graduation: "2026",
      tier: "T1",
      total: 17.0,
      edu: 4.8,
      exp: 3.8,
      proj: 4.2,
      substance: 4.0,
      deploy: 3.5,
      artifact: 1.5,
      skills: 3.8,
      domain: "LLM Finetuning",
      degree: "MS Data Science",
      stream: "Data Science",
      college: "Stanford University",
      location: "San Francisco",
      ai_proj: 4.5,
      fs_proj: 3.0,
      intern_mo: 3.0,
      co_tier: 2.0,
      deploy_stage: "HuggingFace Space",
      num_skills: 10,
      claude_lvl: "Intermediate",
      aiml_exp: "12 months data analysis and fine-tuning experiments",
      demo_explanation: "Fine-tuning pipeline with weights hosted on Hugging Face.",
      demo_review_notes_ai: "Claude Evaluation: Sofia exhibits high capability in model parameter tuning and hyperparameter optimization. Her dataset curation and prep logic are outstanding. The project is hosted on HuggingFace Spaces but lacks a custom UI wrapper, which lowers the deployment score slightly. Substance is solid.",
      mg_review: "Looks good.",
      mg_interview_priority: "Medium",
      review_comments: "Excellent school tier background. Stanford MS data sciences candidate.",
      app_status: "Yes",
      eval_group: "Jal"
    },
    round_2_evaluation: {
      when_can_they_start: "01-09-2026",
      duration_months: "3 months",
      demo_review_comment: "Demonstrated fine-tuning results. The stack is clean. Good grasp of training mechanics, though deployment details are generic.",
      product_depth: "Good dataset cleanup routines, training code is reproducible.",
      complexity: "Medium",
      tech_stack: "Python, PyTorch, HuggingFace Transformers, LoRA",
      solves_business_problem: "Yes",
      moved_to_round_3: "Maybe"
    },
    round_3_evaluation: {
      review_comments: "Recruiter to review start dates alignment. Standard competency is high.",
      final_status: ""
    }
  },
  {
    id: 3,
    submission_date: "2026-07-03T09:40:22Z",
    full_name: "Rahul Verma",
    email: "rahul.verma@nit.edu",
    phone: "+91 87654 32109",
    linkedin: "https://linkedin.com/in/rahulverma",
    location: "Delhi, India",
    preferred_start_date: "2026-08-01",
    education_level: "B.Tech",
    ug_university: "NIT Trichy",
    masters_university: null,
    course_major: "Electronics",
    degree_status: "Graduated",
    completion_year: 2025,
    programming_languages: "Python, C++, Java",
    aiml_experience: "Under 1 Year",
    claude_ecosystem: "Tier 1",
    skill_python: 3,
    skill_deep_learning: 3,
    skill_nlp: 2,
    skill_computer_vision: 4,
    skill_reinforcement_learning: 1,
    skill_multimodal_ai: 2,
    skill_finetuning_lora_peft: 2,
    skill_llm_orchestration: 3,
    skill_agent_fundamentals: 2,
    skill_mcp: 1,
    skill_embeddings_vector_rag: 3,
    skill_reasoning_models: 2,
    skill_evals: 2,
    skill_ai_coding_tools: 3,
    skill_rag: 3,
    current_project: "Simple web dashboard using Streamlit to classify input images into 5 categories using ResNet.",
    project_state: "Staging",
    project_category: "Computer Vision",
    demo_link: "https://streamlit.nit.edu/rahul-resnet",
    github_url: "https://github.com/rahulverma/resnet-classifier",
    preferred_industry: "Software Engineering",
    open_to_onsite: "Negotiable",
    open_to_travel: "No",
    anything_else: "Looking for an entry level ML role.",
    applied_role: "Software Engineer (ML)",
    job_id: "JOB-SWE-03",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-rahul/view",
    resume_filename: "Rahul_Verma_Resume.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Male",
      cat: "UG",
      graduation: "2025",
      tier: "T2+",
      total: 11.2,
      edu: 3.5,
      exp: 2.0,
      proj: 2.5,
      substance: 2.5,
      deploy: 2.5,
      artifact: 1.0,
      skills: 2.2,
      domain: "Computer Vision",
      degree: "B.Tech ECE",
      stream: "Electronics",
      college: "NIT Trichy",
      location: "Delhi",
      ai_proj: 2.5,
      fs_proj: 2.0,
      intern_mo: 0.0,
      co_tier: 3.0,
      deploy_stage: "Streamlit share",
      num_skills: 5,
      claude_lvl: "Beginner",
      aiml_exp: "6 months simple visual classification projects",
      demo_explanation: "Basic Streamlit loader and image classification loop.",
      demo_review_notes_ai: "Claude Evaluation: Rahul's project utilizes standard out-of-the-box model architecture (ResNet50) without fine-tuning or customized head weights. Code is minimal and relies heavily on tutorial code. Lacks deployment optimization or robust system design. Not recommended for core AI research but could fit general SWE.",
      mg_review: "Accurate evaluation.",
      mg_interview_priority: "Low",
      review_comments: "Candidate skills are slightly basic for the ML Engineer profile.",
      app_status: "Reject",
      eval_group: "Agni"
    },
    round_2_evaluation: null,
    round_3_evaluation: null
  },
  {
    id: 4,
    submission_date: "2026-07-04T14:20:00Z",
    full_name: "Emma Watson",
    email: "emma.watson@oxford.edu",
    phone: "+44 20 7946 0958",
    linkedin: "https://linkedin.com/in/emmawatson-ox",
    location: "London, UK",
    preferred_start_date: "2026-10-01",
    education_level: "Ph.D.",
    ug_university: "Oxford University",
    masters_university: "Oxford University",
    course_major: "Machine Learning",
    degree_status: "Graduated",
    completion_year: 2026,
    programming_languages: "Python, PyTorch, C++, R, Julia",
    aiml_experience: "3+ Years",
    claude_ecosystem: "Tier 3",
    skill_python: 5,
    skill_deep_learning: 5,
    skill_nlp: 4,
    skill_computer_vision: 4,
    skill_reinforcement_learning: 5,
    skill_multimodal_ai: 5,
    skill_finetuning_lora_peft: 4,
    skill_llm_orchestration: 4,
    skill_agent_fundamentals: 4,
    skill_mcp: 3,
    skill_embeddings_vector_rag: 4,
    skill_reasoning_models: 5,
    skill_evals: 4,
    skill_ai_coding_tools: 4,
    skill_rag: 4,
    current_project: "Novel Reinforcement Learning from Human Feedback (RLHF) algorithms optimization for reasoning models.",
    project_state: "Production",
    project_category: "RLHF / Alignment",
    demo_link: "https://oxford.ai/research/rlhf-optimizer",
    github_url: "https://github.com/emmawatson/rlhf-opt",
    preferred_industry: "AI Alignment Lab",
    open_to_onsite: "Negotiable",
    open_to_travel: "Yes",
    anything_else: "Publications in NeurIPS and ICML.",
    applied_role: "Senior AI Researcher",
    job_id: "JOB-RES-01",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-emma/view",
    resume_filename: "Emma_Watson_CV.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Female",
      cat: "PG",
      graduation: "2026",
      tier: "T1+",
      total: 20.8,
      edu: 5.0,
      exp: 5.0,
      proj: 5.0,
      substance: 5.0,
      deploy: 4.8,
      artifact: 2.0,
      skills: 4.0,
      domain: "RLHF / Reasoning",
      degree: "PhD ML",
      stream: "Machine Learning",
      college: "Oxford University",
      location: "London",
      ai_proj: 5.0,
      fs_proj: 3.5,
      intern_mo: 12.0,
      co_tier: 1.0,
      deploy_stage: "Staging and Paper publish",
      num_skills: 14,
      claude_lvl: "Advanced",
      aiml_exp: "40+ months deep reinforcement learning experience",
      demo_explanation: "PyTorch framework implementing novel alignment reward curves.",
      demo_review_notes_ai: "Claude Evaluation: Emma's profile is world-class. Her research on reward reward curves is state-of-the-art. Codebase demonstrates high engineering discipline. Lacks standard commercial full-stack components, but more than makes up for it in algorithmic substance.",
      mg_review: "Stunning profile.",
      mg_interview_priority: "Critical",
      review_comments: "Top tier academic record. Immediate fast-track candidate.",
      app_status: "Yes",
      eval_group: "Vayu"
    },
    round_2_evaluation: {
      when_can_they_start: "01-10-2026",
      duration_months: "12 months",
      demo_review_comment: "Deep discussion. Understands optimizer level mathematics thoroughly.",
      product_depth: "Exceptional code quality and performance profiling.",
      complexity: "High",
      tech_stack: "Python, PyTorch, Triton, CUDA",
      solves_business_problem: "Yes",
      moved_to_round_3: "Yes"
    },
    round_3_evaluation: {
      review_comments: "Outstanding final interview loop. Strongly recommend hire.",
      final_status: "Yes"
    }
  },
  {
    id: 5,
    submission_date: "2026-07-05T10:00:00Z",
    full_name: "Vikram Malhotra",
    email: "vikram@delhitech.edu",
    phone: "+91 99999 11111",
    linkedin: "https://linkedin.com/in/vikramm",
    location: "Delhi, India",
    preferred_start_date: "2026-08-10",
    education_level: "B.Tech",
    ug_university: "DTU Delhi",
    masters_university: null,
    course_major: "Information Technology",
    degree_status: "Graduated",
    completion_year: 2025,
    programming_languages: "Python, Javascript, Rust, HTML/CSS",
    aiml_experience: "1.5 Years",
    claude_ecosystem: "Tier 2",
    skill_python: 4,
    skill_deep_learning: 4,
    skill_nlp: 3,
    skill_computer_vision: 3,
    skill_reinforcement_learning: 2,
    skill_multimodal_ai: 3,
    skill_finetuning_lora_peft: 3,
    skill_llm_orchestration: 4,
    skill_agent_fundamentals: 4,
    skill_mcp: 3,
    skill_embeddings_vector_rag: 4,
    skill_reasoning_models: 3,
    skill_evals: 3,
    skill_ai_coding_tools: 4,
    skill_rag: 4,
    current_project: "Visual RAG system using Claude multimodal APIs to search through company blueprints and PDF reports.",
    project_state: "Staging",
    project_category: "Multimodal AI",
    demo_link: "https://blueprint-rag.vikram.xyz",
    github_url: "https://github.com/vikramm/multimodal-rag",
    preferred_industry: "Enterprise SaaS",
    open_to_onsite: "Yes",
    open_to_travel: "Yes",
    anything_else: "Strong experience building responsive frontends.",
    applied_role: "AI Application Developer",
    job_id: "JOB-DEV-04",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-vikram/view",
    resume_filename: "Vikram_Malhotra_Resume.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Male",
      cat: "UG",
      graduation: "2025",
      tier: "T2",
      total: 15.5,
      edu: 4.2,
      exp: 3.5,
      proj: 4.0,
      substance: 3.8,
      deploy: 4.0,
      artifact: 1.5,
      skills: 3.5,
      domain: "Multimodal RAG",
      degree: "B.Tech IT",
      stream: "Information Technology",
      college: "DTU Delhi",
      location: "Delhi",
      ai_proj: 4.0,
      fs_proj: 4.5,
      intern_mo: 4.0,
      co_tier: 2.0,
      deploy_stage: "Staging URL available",
      num_skills: 9,
      claude_lvl: "Intermediate",
      aiml_exp: "18 months building fullstack apps with AI wrappers",
      demo_explanation: "Multimodal RAG parsing PDF diagrams and blueprints.",
      demo_review_notes_ai: "Claude Evaluation: Vikram's fullstack integration is extremely robust. The frontend is beautiful, responsive, and handles file uploads smoothly. RAG search works well, although vector chunking logic on blueprints could be optimized. Great potential for user-facing AI roles.",
      mg_review: "Solid build.",
      mg_interview_priority: "Medium",
      review_comments: "Very strong fullstack capabilities. Good candidate for engineering.",
      app_status: "Yes",
      eval_group: "Akash"
    },
    round_2_evaluation: {
      when_can_they_start: "10-08-2026",
      duration_months: "6 months",
      demo_review_comment: "Demonstrated full product. Very clean React flow. Well thought out vector storage mechanics.",
      product_depth: "Good RAG integration, frontend logic is pristine.",
      complexity: "Medium",
      tech_stack: "React, Tailwind, Node.js, Pinecone, Claude API",
      solves_business_problem: "Yes",
      moved_to_round_3: "Yes"
    },
    round_3_evaluation: {
      review_comments: "Communication was excellent. Ready to issue offer.",
      final_status: "Yes"
    }
  },
  {
    id: 6,
    submission_date: "2026-07-06T15:00:00Z",
    full_name: "Anika Sharma",
    email: "anika@bits.edu",
    phone: "+91 99887 76655",
    linkedin: "https://linkedin.com/in/anika-sharma",
    location: "Bangalore, India",
    preferred_start_date: "2026-08-20",
    education_level: "B.Tech",
    ug_university: "BITS Pilani",
    masters_university: null,
    course_major: "Computer Science",
    degree_status: "Graduated",
    completion_year: 2025,
    programming_languages: "Python, Javascript, SQL, HTML",
    aiml_experience: "1 Year",
    claude_ecosystem: "Tier 2",
    skill_python: 4,
    skill_deep_learning: 3,
    skill_nlp: 4,
    skill_computer_vision: 2,
    skill_reinforcement_learning: 1,
    skill_multimodal_ai: 3,
    skill_finetuning_lora_peft: 2,
    skill_llm_orchestration: 4,
    skill_agent_fundamentals: 3,
    skill_mcp: 2,
    skill_embeddings_vector_rag: 4,
    skill_reasoning_models: 3,
    skill_evals: 3,
    skill_ai_coding_tools: 4,
    skill_rag: 4,
    current_project: "LLM agent helper to automate drafting customized sales outreach emails based on LinkedIn profiles.",
    project_state: "Staging",
    project_category: "Agent Applications",
    demo_link: "https://sales-agent.anika.dev",
    github_url: "https://github.com/anikasharma/sales-outreach-agent",
    preferred_industry: "SaaS / SalesTech",
    open_to_onsite: "Yes",
    open_to_travel: "Negotiable",
    anything_else: "Completed a 6 month internship in a growth stage startup.",
    applied_role: "Software Developer (AI Systems)",
    job_id: "JOB-DEV-05",
    rubric_id: "RUBRIC-V2",
    screening_type: "Standard",
    resume_drive_url: "https://drive.google.com/file/d/sample-anika/view",
    resume_filename: "Anika_Sharma_Resume.pdf",
    analysis_status: "Completed",
    round_1_evaluation: {
      gender: "Female",
      cat: "UG",
      graduation: "2025",
      tier: "T1",
      total: 14.8,
      edu: 4.5,
      exp: 3.0,
      proj: 3.5,
      substance: 3.5,
      deploy: 3.8,
      artifact: 1.5,
      skills: 3.5,
      domain: "Agent Workflows",
      degree: "B.Tech CS",
      stream: "Computer Science",
      college: "BITS Pilani",
      location: "Bangalore",
      ai_proj: 3.5,
      fs_proj: 4.0,
      intern_mo: 6.0,
      co_tier: 2.0,
      deploy_stage: "Vercel live deployment",
      num_skills: 8,
      claude_lvl: "Intermediate",
      aiml_exp: "12 months agent building experience",
      demo_explanation: "Sales assistant scraping info and drafting personalized email outreach.",
      demo_review_notes_ai: "Claude Evaluation: Anika has built a very practical automation workflow. Email outputs are well-crafted using prompt engineering frameworks. Code is clean and functional, utilizing standard APIs. System latency could be improved via parallelizing scraper threads, but overall a solid delivery.",
      mg_review: "Looks solid.",
      mg_interview_priority: "Medium",
      review_comments: "Interesting practical utility. Good college tier (BITS).",
      app_status: "Maybe",
      eval_group: "Bijli"
    },
    round_2_evaluation: null,
    round_3_evaluation: null
  }
];
